fractal:
    width: 1920
    height: 1080
    horizontal: False
    vertical: False
    iterations: 10000000
    threads: 1


transformations:
    - transformation: [0.5, 0.0, 0.0, 0.5, -1.0, 1.0]
      chance: 0.2
    - transformation: [0.5, 0.0, 0.0, 0.5, 1.0, -1.0]
      chance: 0.2
    - transformation: [0.5, 0.5, -0.5, 0.5, -1.0, -1.0]
      chance: 0.2
    - transformation: [0.3, -0.3, 0.3, 0.3, 0.0, 1.0]
      chance: 0.1
    - transformation: [0.6, -0.6, 0.6, 0.6, 1.0, 0.0]
      chance: 0.1
    - transformation: [0.4, 0.4, -0.4, 0.4, -0.5, -0.5]
      chance: 0.1
    - transformation: [0.7, 0.3, -0.3, 0.7, 0.5, 0.5]
      chance: 0.1
# possible variations: bubble, heart, spherical, swirl;
variations:
    - name: "heart"
      chance: 0.25
    - name: "swirl"
      chance: 0.25
    - name: "spherical"
      chance: 0.25
    - name: "bubble"
      chance: 0.25
