fractal:
    width: 1920
    height: 1080
    horizontal: False
    vertical: False
    iterations: 10000000
    threads: 10

transformations:
    - transformation: [0.5, 0.0, 0.0, 0.5, -1.0, 1.0]
      chance: 0.25
    - transformation: [0.5, 0.0, 0.0, 0.5, 1.0, -1.0]
      chance: 0.25
    - transformation: [0.5, 0.5, -0.5, 0.5, -1.0, -1.0]
      chance: 0.25
# possible variations: bubble, heart, spherical, swirl;
variations:
    - name: "heart"
      chance: 0.25
    - name: "swirl"
      chance: 0.25
